add perl and python download methods

diff --git a/views/install.sh.erb b/views/install.sh.erb
--- a/views/install.sh.erb
+++ b/views/install.sh.erb
@@ -252,14 +252,42 @@ do_curl() {
   fi
 }
 
+# do_curl(URL, FILENAME)
+do_perl() {
+  perl -e 'use LWP::Simple; getprint($ARGV[0]);' "$1" > "$2"
+  # check for bad return status
+  [ $? -ne 0 ] && unable_to_retrieve_package
+  # check for bad output or empty file
+  # grep "The specified key does not exist." "$2" 2>&1 >/dev/null
+  # if [ $? -eq 0 ] || [ ! -s "$2" ]; then
+  #   unable_to_retrieve_package
+  # fi
+}
+
+# do_curl(URL, FILENAME)
+do_python() {
+  python -c "import sys,urllib2 ; sys.stdout.write(urllib2.urlopen(sys.argv[1]).read())" "$1" > "$2"
+  # check for bad return status
+  [ $? -ne 0 ] && unable_to_retrieve_package
+  # check for bad output or empty file
+  #grep "The specified key does not exist." "$2" 2>&1 >/dev/null
+  #if [ $? -eq 0 ] || [ ! -s "$2" ]; then
+  #  unable_to_retrieve_package
+  #fi
+}
+
 # do_download(URL, FILENAME)
 do_download() {
   if [ "x$downloader" = "xcurl" ]; then
     do_curl($1, $2)
   elif [ "x$downloader" = "xwget" ]; then
     do_wget($1, $2)
+  elif [ "x$downloader" = "xperl" ]; then
+    do_perl($1, $2)
+  elif [ "x$downloader" = "xpython" ]; then
+    do_python($1, $2)
   else
-    echo "Only know how to download via curl or wget!"
+    echo "Only know how to download via curl, wget, perl and python!"
     exit 5
   fi
 }
@@ -296,8 +324,12 @@ if exists wget; then
   downloader="wget"
 elif exists curl; then
   downloader="curl"
+elif exists perl; then
+  downloader="perl"
+elif exists python; then
+  downloder="python"
 else
-  echo "Cannot find wget or curl - cannot install Chef!"
+  echo "Cannot find wget, curl, perl or python - cannot install Chef!"
   exit 5
 fi
 
